stages:
  - ssh-publickey
  - prerequisites-install
  - install-terraform
  - configure-ansible
  - deploy
  
  - destroy
  

ssh-publickey:
  stage: ssh-publickey
  script: 
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $PUBLICKEY > ~/.ssh/gitlab.pub
    - cd ~/.ssh
  tags:
    - banuka

prerequisites-install:
  stage: prerequisites-install
  script:
    - echo "hi"
    - sudo yum update -y && sudo yum install wget unzip -y
  tags:
    - banuka

install_terraform:
  stage: install-terraform
  script:
    - export VER="0.12.9"
    - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
    - unzip terraform_${VER}_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - which terraform
  tags:
    - banuka

deploy:
  stage: deploy
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve
  tags:
    - banuka

configure-ansible:
  stage: configure-ansible
  script:
    - e

destroy:
  stage: destroy
  script:
    - terraform init
    # - terraform destroy --auto-approve
  tags:
    - banuka

