stages:
  - install-terraform
  - provision-kube-master
  
  - destroy
  

before_script:
    - echo "hi"
    - sudo yum update -y && sudo yum install wget unzip -ys

install_terraform:
  stage: install-terraform
  script:
    - export VER="0.12.9"
    - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
    - unzip terraform_${VER}_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - which terraform
  tags:
    - banuka

provision-kube-master:
  stage: provision-kube-master
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve

  tags:
    - banuka

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve
  tags:
    - banuka
