stages:
  - apply

apply:
  stage: apply
  script:
    - echo "hi"
    - sudo yum update
    - sudo yum install httpd -y
    - sudo echo "<h1>Hello This is done with Gitlab CI</h1>" > /var/www/html/index.html
    - sudo systemctl start httpd
    - sudo systemctl enable httpd
  tags:
    - banuka
