stages:
  - ssh-publickey
  - prerequisites-install
  - install-terraform
  - configure-ansible
  - deploy
  
  - destroy
  
ssh-publickey:
  stage: ssh-publickey
  script: 
    - pwd
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - |
      #!/bin/bash
      cd
      FILE1="$PWD/gitlab.pem"

      if $FILE1; then
        echo "$FILE1 exists"
        chmod 700 $FILE1
        echo $PRIVATEKEY > ~/.ssh/gitlab.pem
        sudo chmod 400 ~/.ssh/gitlab.pem
        echo $PUBLICKEY > ~/.ssh/gitlab.pub
      else 
        echo "$FILE does not exist"
      fi

      FILE2="/home/ec2-user/.ssh/id_rsa"

      if $FILE2; then
        echo "$FILE2 exists"
        sudo chmod 700 $FILE2

        sudo chmod 700 /home/ec2-user/.ssh/id_rsa
        sudo cp ~/.ssh/gitlab.pem /home/ec2-user/.ssh/id_rsa
        sudo chmod 400 /home/ec2-user/.ssh/id_rsa
        sudo cp ~/.ssh/gitlab.pub /home/ec2-user/.ssh/id_rsa.pub
      else 
        echo "$FILE does not exist"
      fi


    - cd ~/.ssh
    - sudo cd /home/ec2-user/
    - pwd
  tags:
    - banuka

prerequisites-install:
  stage: prerequisites-install
  script:
    - echo "hi"
    - sudo yum update -y && sudo yum install wget unzip -y
  tags:
    - banuka

install_terraform:
  stage: install-terraform
  script:
    - export VER="0.12.9"
    - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
    - unzip terraform_${VER}_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - which terraform
  tags:
    - banuka

deploy:
  stage: deploy
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve
  tags:
    - banuka

configure-ansible:
  stage: configure-ansible
  script:
    - pwd
  tags:
    - banuka

destroy:
  stage: destroy
  script:
    - terraform init
    # - terraform destroy --auto-approve
  tags:
    - banuka

    

