stages:
  - prerequisites-install
  - install-terraform
  - configure-tf-backend
  - provision-kube-master
  
  - destroy
  

prerequisites-install:
  stage: prerequisites-install
  script:
    - echo "hi"
    - sudo yum update -y && sudo yum install wget unzip -y
  tags:
    - banuka

install_terraform:
  stage: install-terraform
  script:
    - export VER="0.12.9"
    - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
    - unzip terraform_${VER}_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - which terraform
  tags:
    - banuka

configure-tf-backend:
  stage: configure-tf-backend
  script:
    - cd backend/
    - terraform init
  tags:
    - banuka

provision-kube-master:
  stage: provision-kube-master
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve

  tags:
    - banuka

destroy:
  stage: destroy
  script:
    - terraform init
    - terraform destroy --auto-approve
  tags:
    - banuka
    