stages:
  - apply

apply:
  stage: apply
  script:
    - echo "hi"
    - sudo su -
    - sudo apt-get install httpd -y
    - sudo systemctl start httpd
    - sudo systemctl enable httpd
  tags:
    - banuka