---
- hosts: kube-master
  tasks:
    - name: Print the value
      become: true
      shell: |
        kubeadm token create --print-join-command 2> /dev/null
      register: token

    - name: set fact
      set_fact:
        myvar: "{{ token.stdout }}"

- hosts: kube-minions
  tasks:
    - name: Print the variable
      become: true
      shell: |
        echo {{myvar}}