---
- hosts: kube-master
  tasks:
    - name: Print the value
      become: true
      shell: |
        echo "hi"
      set_fact:
        banuka: <value-taken-from-above-shell-command>

- hosts: kube-minions
  tasks:
    - name: Print the variable
      become: true
      shell: |
        echo {{banuka}}