---
- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: ubuntu
      apt:
        upgrade: yes
        update_cache: yes

    - name: install apt-transport-https
      become: ubuntu
      apt: update_cache=yes force_apt_get=yes

    - name: APT Key
      become: true
      shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"

    - name: create folder if not exists
      become: true
      file:
        path: /etc/apt/sources.list.d
        state: directory
        owner: root
        group: root
        mode: 0775

    - name: create file
      become: true
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: touch

    - name: write to the file
      become: true
      copy: content="deb https://apt.kubernetes.io/ kubernetes-xenial main" dest="/etc/apt/sources.list.d/kubernetes.list"

    - name: Update and upgrade apt packages
      become: ubuntu
      apt:
        upgrade: yes
        update_cache: yes

    - name: Disable Swap Memory One
      become: true
      shell: "swapoff -a / swapoff -a"

    - name: Disable Swap Memory
      become: true
      shell: |      
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab / sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab      
