---
- hosts: all
  become: ubuntu
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
          
